
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, MessageSquare, Brain, TrendingUp, Download, Sparkles, FileDown } from 'lucide-react';
import { Button } from "@/components/ui/button";
import { createPageUrl } from '../utils';
import AuthGuard from '../components/AuthGuard';
import OnboardingGuard from '../components/OnboardingGuard';
import OnboardingWelcome from '../components/OnboardingWelcome';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Link } from 'react-router-dom';

export default function Dashboard() {
  const { data: user } = useQuery({
    queryKey: ['user'],
    queryFn: () => base44.auth.me()
  });

  const { data: orders = [] } = useQuery({
    queryKey: ['content-orders'],
    queryFn: () => base44.entities.ContentOrder.list('-created_date'),
    enabled: !!user
  });



  const stats = [
    {
      title: 'Total Orders',
      value: orders.length,
      icon: FileText,
      color: 'bg-blue-500'
    },

    {
      title: 'Available Models',
      value: 7,
      icon: Brain,
      color: 'bg-green-500'
    },
    {
      title: 'Processing',
      value: orders.filter(d => d.status === 'processing').length,
      icon: TrendingUp,
      color: 'bg-orange-500'
    }
  ];

  const hasOrders = orders.length > 0;

  return (
    <AuthGuard>
      <OnboardingGuard>
      <TooltipProvider>
      <div className="p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">Order Delivery</h1>
        <p className="text-gray-400">Welcome to your A.I. orchestration hub</p>
      </div>
      
      <OnboardingWelcome />

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {stats.map((stat) => {
          const Icon = stat.icon;
          const tooltips = {
            'Total Orders': 'Total number of content orders you\'ve created',
            'Available Models': 'A.I. models available for content generation',
            'Processing': 'Orders currently being generated by A.I.'
          };
          
          return (
            <Tooltip key={stat.title}>
              <TooltipTrigger asChild>
                <Card className="bg-[#1A1A1A] border-gray-800 hover:border-purple-500 transition-colors cursor-help">
                  <CardHeader className="flex flex-row items-center justify-between pb-1 pt-3 px-4">
                    <CardTitle className="text-sm font-medium text-gray-400">
                      {stat.title}
                    </CardTitle>
                    <div className={`p-1.5 rounded-lg ${stat.color} bg-opacity-20`}>
                      <Icon className={`w-3.5 h-3.5 ${stat.color.replace('bg-', 'text-')}`} />
                    </div>
                  </CardHeader>
                  <CardContent className="px-4 pb-3">
                    <div className="text-2xl font-bold text-white">{stat.value}</div>
                  </CardContent>
                </Card>
              </TooltipTrigger>
              <TooltipContent>
                <p>{tooltips[stat.title]}</p>
              </TooltipContent>
            </Tooltip>
          );
        })}
      </div>

      <div className="grid grid-cols-1 gap-6">
        <Card className="bg-[#1A1A1A] border-gray-800">
          <CardHeader>
            <CardTitle className="text-white">Recent Orders</CardTitle>
          </CardHeader>
          <CardContent>
            {orders.length === 0 ? (
              <p className="text-gray-500 text-sm">No orders yet</p>
            ) : (
              <div className="space-y-3">
                {orders.slice(0, 5).map((order) => (
                  <div key={order.id} className="flex items-center justify-between p-3 bg-[#0D0D0D] rounded-lg border border-gray-800">
                    <div className="flex items-center gap-3 flex-1">
                      <FileText className="w-4 h-4 text-purple-500" />
                      <div className="flex-1">
                        <div className="text-white text-sm font-medium">{order.title || 'Untitled Order'}</div>
                        <div className="text-xs text-gray-500 capitalize">{order.task_type.replace('_', ' ')}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className={`text-xs px-2 py-1 rounded font-medium ${
                        order.status === 'completed' ? 'bg-green-500 bg-opacity-20 text-green-400' :
                        order.status === 'processing' ? 'bg-yellow-500 bg-opacity-20 text-yellow-400' :
                        'bg-red-500 bg-opacity-20 text-red-400'
                      }`}>
                        {order.status === 'completed' ? 'Ready' : order.status === 'processing' ? 'Processing' : 'Failed'}
                      </div>
                      {order.status === 'completed' && order.output_content && (
                        <Button 
                          size="sm"
                          onClick={async () => {
                            try {
                              const blob = new Blob([order.output_content], { type: 'text/plain' });
                              const url = window.URL.createObjectURL(blob);
                              const a = document.createElement('a');
                              a.href = url;
                              a.download = `${order.title || 'content'}-${order.id}.txt`;
                              document.body.appendChild(a);
                              a.click();
                              window.URL.revokeObjectURL(url);
                              a.remove();
                            } catch (error) {
                              // Error handled by toast notification
                              alert('Download failed. Please try again.');
                            }
                          }}
                          className="bg-purple-600 hover:bg-purple-700 h-7 px-2"
                        >
                          <Download className="w-3 h-3" />
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>


      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
        <Card className="bg-[#1A1A1A] border-gray-800 hover:border-purple-500 transition-colors">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <FileDown className="w-5 h-5 text-purple-500" />
              Sales Sheet
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-400 text-sm mb-4">
              Comprehensive overview of OmniMind24 features, pricing, and benefits
            </p>
            <Button
              onClick={async () => {
                const response = await base44.functions.invoke('generateSalesSheet');
                const blob = new Blob([response.data], { type: 'application/pdf' });
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'OmniMind24-Sales-Sheet.pdf';
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
                a.remove();
              }}
              className="w-full bg-purple-600 hover:bg-purple-700"
            >
              <Download className="w-4 h-4 mr-2" />
              Download Sales Sheet
            </Button>
          </CardContent>
        </Card>

        <Card className="bg-[#1A1A1A] border-gray-800 hover:border-purple-500 transition-colors">
          <CardHeader>
            <CardTitle className="text-white flex items-center gap-2">
              <FileDown className="w-5 h-5 text-blue-500" />
              Technical Documentation
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-400 text-sm mb-4">
              Complete technical guide for developers and programmers
            </p>
            <Button
              onClick={async () => {
                const response = await base44.functions.invoke('generateTechnicalSheet');
                const blob = new Blob([response.data], { type: 'application/pdf' });
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'OmniMind24-Technical-Documentation.pdf';
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
                a.remove();
              }}
              className="w-full bg-blue-600 hover:bg-blue-700"
            >
              <Download className="w-4 h-4 mr-2" />
              Download Technical Docs
            </Button>
          </CardContent>
        </Card>
      </div>
      </div>
      </TooltipProvider>
      </OnboardingGuard>
      </AuthGuard>
      );
      }