import { apiClient } from './client';

// Export function wrappers
export const chatWithLLM = apiClient.functions.chatWithLLM;
export const updateModelBenchmarks = apiClient.functions.updateModelBenchmarks;
export const selectOptimalModel = apiClient.functions.selectOptimalModel;
export const syncSalesforceTasks = apiClient.functions.syncSalesforceTasks;
export const syncRealTimeBenchmarks = apiClient.functions.syncRealTimeBenchmarks;
export const processOrder = apiClient.functions.processOrder;
export const createPaymentIntent = apiClient.functions.createPaymentIntent;
export const stripeWebhook = apiClient.functions.stripeWebhook;
export const triggerAutoPurchase = apiClient.functions.triggerAutoPurchase;
export const generateContentIdeas = apiClient.functions.generateContentIdeas;
export const uploadToS3 = apiClient.functions.uploadToS3;
export const redeemReferral = apiClient.functions.redeemReferral;
export const sendResendEmail = apiClient.functions.sendResendEmail;
export const resetOnboarding = apiClient.functions.resetOnboarding;
export const analyzeSEO = apiClient.functions.analyzeSEO;
export const startFineTuning = apiClient.functions.startFineTuning;
export const makeStaff = apiClient.functions.makeStaff;
export const testElevenlabs = apiClient.functions.testElevenlabs;
export const testTavily = apiClient.functions.testTavily;
export const testStripe = apiClient.functions.testStripe;
export const exportContent = apiClient.functions.exportContent;
export const exportAudio = apiClient.functions.exportAudio;
export const generateSalesSheet = apiClient.functions.generateSalesSheet;
export const generateTechnicalSheet = apiClient.functions.generateTechnicalSheet;
export const supportChatbot = apiClient.functions.supportChatbot;
export const createPaymentIntentx = apiClient.functions.createPaymentIntentx;
export const stripeWebhookx = apiClient.functions.stripeWebhookx;
export const completeTestOrder = apiClient.functions.completeTestOrder;
export const verifyCheckoutSession = apiClient.functions.verifyCheckoutSession;
export const makeAdmin = apiClient.functions.makeAdmin;
export const completeOrder = apiClient.functions.completeOrder;
export const refundOrder = apiClient.functions.refundOrder;
export const cleanupStuckOrders = apiClient.functions.cleanupStuckOrders;
export const rateLimitCheck = apiClient.functions.rateLimitCheck;
